/* Pulls the CSS the site actually ships and writes it as the Storybook's
   stylesheet, so the library can never drift from production. Astro scopes
   page styles with a data-astro-cid attribute; those are stripped, since the
   story markup is the same classes without Astro's compile-time hashes.

   Usage: node sync-css.mjs [origin]   default http://localhost:4321 */
import { writeFileSync, mkdirSync } from 'node:fs';

const ORIGIN = process.argv[2] || 'http://localhost:4321';
const PAGES = ['/', '/work/paypal', '/design-systems', '/resume', '/work'];

const seen = new Set();
const out = [];

for (const path of PAGES) {
  const html = await fetch(ORIGIN + path).then((r) => r.text());
  const blocks = html.match(/<style[^>]*>([\s\S]*?)<\/style>/g) || [];
  for (const block of blocks) {
    let css = block.replace(/^<style[^>]*>/, '').replace(/<\/style>$/, '');
    // Astro's scope hash is compile-time noise; the class names are the contract.
    css = css.replace(/\[data-astro-cid-[a-z0-9]+\]/g, '');
    css = css.trim();
    if (!css || seen.has(css)) continue;
    seen.add(css);
    out.push(`/* ---- from ${path} ---- */\n${css}`);
  }
}

mkdirSync(new URL('./src/', import.meta.url), { recursive: true });
const header = `/* GENERATED by sync-css.mjs on ${new Date().toISOString().slice(0, 10)}.
   Do not edit. This is the CSS stevendesignco.com ships, pulled from the
   running site, so every story below renders with production styles. */\n\n`;
writeFileSync(new URL('./src/sdc.css', import.meta.url), header + out.join('\n\n'));
console.log(`wrote src/sdc.css from ${PAGES.length} pages, ${out.length} blocks, ${header.length + out.join('').length} bytes`);
